-- MySQL Script generated by MySQL Workbench
-- Sat Nov  8 13:38:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dsr_projekt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dsr_projekt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dsr_projekt` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dsr_projekt` ;

-- -----------------------------------------------------
-- Table `dsr_projekt`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dsr_projekt`.`User` ;

CREATE TABLE IF NOT EXISTS `dsr_projekt`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(50) NULL DEFAULT NULL,
  `priimek` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `geslo` VARCHAR(255) NULL DEFAULT NULL,
  `vloga` ENUM('uporabnik', 'administrator') NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dsr_projekt`.`Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dsr_projekt`.`Reservation` ;

CREATE TABLE IF NOT EXISTS `dsr_projekt`.`Reservation` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL ,
  `datum` DATE NULL DEFAULT NULL,
  `ura` TIME NULL DEFAULT NULL,
  `stevilo_oseb` INT NULL,
  `status` ENUM('potrjena', 'cakajoca', 'zavrnjen') NULL DEFAULT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `reservation_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dsr_projekt`.`User` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dsr_projekt`.`PDFConfirmation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dsr_projekt`.`PDFConfirmation` ;

CREATE TABLE IF NOT EXISTS `dsr_projekt`.`PDFConfirmation` (
  `pdf_id` INT NOT NULL AUTO_INCREMENT,
  `reservation_id` INT NULL DEFAULT NULL,
  `pot_potrdila` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`pdf_id`),
  UNIQUE INDEX `reservation_id` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `pdfconfirmation_ibfk_1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `dsr_projekt`.`Reservation` (`reservation_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dsr_projekt`.`TableEntity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dsr_projekt`.`TableEntity` ;

CREATE TABLE IF NOT EXISTS `dsr_projekt`.`TableEntity` (
  `table_id` INT NOT NULL AUTO_INCREMENT,
  `stevilka` INT NOT NULL,
  `kapaciteta` INT NULL DEFAULT NULL,
  `lokacija` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`table_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dsr_projekt`.`Reservation_Table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dsr_projekt`.`Reservation_Table` ;

CREATE TABLE IF NOT EXISTS `dsr_projekt`.`Reservation_Table` (
  `reservation_id` INT NOT NULL,
  `table_id` INT NOT NULL,
  INDEX `table_id` (`table_id` ASC) VISIBLE,
  CONSTRAINT `reservation_table_ibfk_1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `dsr_projekt`.`Reservation` (`reservation_id`),
  CONSTRAINT `reservation_table_ibfk_2`
    FOREIGN KEY (`table_id`)
    REFERENCES `dsr_projekt`.`TableEntity` (`table_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
